spring.datasource.url=jdbc:oracle:thin:@211.110.44.40:1521:o
spring.datasource.username=WIPLAT
spring.datasource.password=twowincall
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# MyBatis ??
mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.type-aliases-package=com.twocrm.model

spring.mvc.view.prefix= /WEB-INF/jsp/
spring.mvc.view.suffix= .jsp

# SQL ?? ? ??
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ?????, ?? ??? ?? ? ??? ??? ???? ? ????.
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE