spring.datasource.url=jdbc:oracle:thin:@211.110.44.40:1521:o
spring.datasource.username=twowincall
spring.datasource.password=twowincall
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

